
const CONTACT_US_FORM_SUBMISSION_ENDPOINT = process.env.NUXT_ENV_CONTACT_US_FORM_SUBMISSION_ENDPOINT

const LC_API_KEY = process.env.NUXT_ENV_LC_API

export {
  CONTACT_US_FORM_SUBMISSION_ENDPOINT,
  LC_API_KEY
}
