
const CONTACT_US_FORM_SUBMISSION_ENDPOINT = process.env.NUXT_ENV_CONTACT_US_FORM_SUBMISSION_ENDPOINT

const LC_API_KEY = process.env.NUXT_ENV_LC_API

const PRODUCTION_DOMAIN = 'unizen.io'

export {
  CONTACT_US_FORM_SUBMISSION_ENDPOINT,
  LC_API_KEY,
  PRODUCTION_DOMAIN
}
